# -*- coding: utf-8 -*-
"""Pandas Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17C8MI5glRFFomz0MJa4na_G_ZbxPnSFv

# From Chaos to Clarity: Cleaning & Analyzing Real-world Messy Data
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# import data
df= pd.read_csv('dirty_cafe_sales.csv')

"""### Read data set"""

df.shape
df.head()
df.info()
df.describe()

"""### Standardize column names"""

# df.head(10)
df.rename(columns={
    'Transaction ID':'id',
    'Price Per Unit':'price',
    'Total Spent':'total',
    'Payment Method':'pmethod',
    'Transaction Date':'date',
    'Item':'item',
    'Quantity':'quantity',
    'Location':'location',
    }, inplace=True)

# df.coulmns=df.columns.str.lower() # did not work
df.head()

"""### Fix data types:"""

df.dtypes
df.quantity= pd.to_numeric(df.quantity,errors='coerce')
df.quantity.describe()
df.price= pd.to_numeric(df.price,errors='coerce')
df.total= pd.to_numeric(df.total,errors='coerce')
df.date = pd.to_datetime(df.date,errors='coerce')
df["month"] = df.date.dt.month
df["day"] = df.date.dt.day_of_week
df.describe()

"""### Validatin and correctness"""

# df[df.id.duplicated()].sum()
# df = df.drop_duplicates()
# There is no duplicates

df[df.price <= 0]
df[df.quantity <= 0]
df[df.total < df.price * df.quantity]
# All is good

df[df.total != df.price*df.quantity] # there is error values in 1456 rows
df.loc[
    (df['quantity'].notnull()) &
    (df['price'].notnull()) &
    (df['total'].isnull()),
    'total'
] = df['price'] * df['quantity']
# we have fixed 475 rows
df[df.total != df.price * df.quantity] # 994 rows is remaining
#look where we can get price from total/quantity
df.loc[(df['quantity'].notnull()) & (df['price'].isnull()) & (df['total'].notnull())] # we found 495 rows

df.loc[
    (df['quantity'].notnull()) &
    (df['price'].isnull()) &
    (df['total'].notnull()),
    'price'
] = df['total'] / df['quantity']

#look where we can get quantity from total/price

df.loc[(df['quantity'].isnull()) & (df['price'].notnull()) & (df['total'].notnull())] # we found 441 rows

df.loc[
    (df['quantity'].isnull()) &
    (df['price'].notnull()) &
    (df['total'].notnull()),
    'quantity'
] = df['total'] / df['price']

# Finally we will look for all null then delete them
df.loc[(df['quantity'].isnull()) & (df['price'].isnull()) & (df['total'].isnull())] # we found 0 rows

# df.info()
df[df.total != df.price * df.quantity].shape # there is still 58 rows with 2 out of 3 is null

# find out the ones with price is null
df[(df.total != df.price * df.quantity)& (df.price.isnull())].shape # 38 rows we can fix
df[(df.total != df.price * df.quantity)& (df.price.isnull())]

# get the price and reassign it
df.groupby(['item','price']).price.count()
# Cake=3, Coffee=2, Cookie=1,Juice=3, Salad=5, Sandwich=4, Smoothie=4, Tea=1.5
prices = {"Cake": 3, "Coffee": 2, "Cookie": 1, "Juice": 3, "Salad": 5, "Sandwich": 4, "Smoothie": 4, "Tea": 1.5}
# I found out that i can solve ERROR and UNKNOWN in item ;)

df.loc[(df.total != df.price * df.quantity)& (df.price.isnull()),['item','price']]
df.loc[df['price'].isnull(), 'price'] = df.loc[df['price'].isnull(), 'item'].map(prices)
df.loc[(df.total != df.price * df.quantity)& (df.price.isnull()),['item','price']]
df[df.total != df.price * df.quantity].shape # now its 26 rows

# Its about time to fix items
df.loc[(df.item.isnull())| (df.item=='ERROR') | (df.item=='UNKNOWN')] # 969 rows

# Invert dictionary: price → item
price_to_item = {v: k for k, v in prices.items()}

# Fill missing/invalid items based on price
df.loc[
    (df['item'].isnull()) | (df['item'].isin(['ERROR', 'UNKNOWN'])),
    'item'
] = df.loc[
    (df['item'].isnull()) | (df['item'].isin(['ERROR', 'UNKNOWN'])),
    'price'
].map(price_to_item)

df.loc[(df.item.isnull())| (df.item=='ERROR') | (df.item=='UNKNOWN')] # now its 6 rows.


# lets fix payment method
df.groupby('pmethod').total.count() # ERROR	305, UNKNOWN	293
# df[df.pmethod.isnull()].shape # 2579 NaN
df['pmethod'].value_counts(normalize=True)
df[df['pmethod'].isna()].groupby('location')['total'].mean()

# best practice is to treat missing values as Unknown
df['pmethod'] = df['pmethod'].replace(['ERROR', 'UNKNOWN'], np.nan)
df['pmethod'] = df['pmethod'].fillna('Unknown')
df.groupby('pmethod').total.count() # Unknown	3169

# lets fix payment method
df.groupby('location').total.count() # ERROR	357, UNKNOWN	338
df[df.location.isnull()].shape # 3265 NaN
df['location'].value_counts(normalize=True)

df['location'] = df['location'].replace(['ERROR', 'UNKNOWN'], np.nan)
df['location'] = df['location'].fillna('Unknown')
df.groupby('location').total.count() # Unknown	3953

# Delete time

df[(df.pmethod=='Unknown')&(df.location=='Unknown')& df.date.isna()]

"""### Talk to the data"""

item_tpq=df.groupby('item')[['total','price','quantity']].agg(['sum','count']).sort_values(by=('total','sum'),ascending=False)
item_tpq

"""Here we can see that the most sold item is **Juice**, and the least one is **Tea**, while on money scale the best income item is **Salad** while **Cookie** is the least."""

df.groupby('pmethod').total.sum().sort_values(ascending=False)

"""Here we can tell that all payment methods are almost the same."""

df.groupby('location').total.sum().sort_values(ascending=False)

"""Here we notice that the location didn't make a quit change in total income."""

df.groupby(['location','pmethod'])[['total','quantity']].sum()

"""There is no relation between location and payment method."""

total_day=df.loc[df.total.notnull(),['date','total']].groupby('date').sum().sort_values(by='total',ascending=False)
total_day

"""We can tell that some days are better than others. but why?"""

month_tq=df.groupby('month')[['total','quantity']].sum().sort_values(by='total',ascending=False)
month_tq

itemonth=df.groupby(['month','item'])[['quantity','total']].sum().sort_values(by='total',ascending=False)
itemonth

"""### Time to see the data:"""

sns.barplot(data=month_tq, x='month', y='total')
plt.title('Barplot of Monthly Daily Income')
plt.xlabel('Month')
plt.ylabel('Daily Income Sum')
plt.show()

sns.scatterplot(data= itemonth,x='month', y='total')
plt.title('Scatterplot of Monthly Daily Income')
plt.xlabel('Item Name')
plt.ylabel('Month Number')
plt.show()

sns.scatterplot(data= df,x='price', y='quantity')
plt.title('Scatterplot of price & quantity')
plt.xlabel('Price')
plt.ylabel('Quantity')
plt.show()

sns.heatmap(df.isna(), cbar=False)